spring.application.name=server
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
okta.oauth2.issuer=https://dev-ccqkvb14q4wkazd6.us.auth0.com/
okta.oauth2.client-id=Vx4nTobhToIUeUGG7pfU8MZzQlVxlT8U
okta.oauth2.client-secret=${AUTH0_CLIENT_SECRET}
okta.oauth2.audience="http://localhost:8080/"
auth0.domain=dev-ccqkvb14q4wkazd6.us.auth0.com
auth0.audience=http://localhost:8080/