micronaut.application.name=server
micronaut.security.enabled=true
micronaut.security.token.cookie.enabled=true
micronaut.security.token.cookie.cookie-http-only=true
micronaut.security.authentication=idtoken
micronaut.security.oauth2.clients.auth0.client-id=J49enmYEIqkzDdzS7gFPXIn4CbPpdKKy
micronaut.security.oauth2.clients.auth0.client-secret=${AUTH0_CLIENT_SECRET}
micronaut.security.oauth2.clients.auth0.openid.issuer=https://dev-ccqkvb14q4wkazd6.us.auth0.com/
micronaut.security.oauth2.clients.auth0.scopes[0]=openid
micronaut.security.oauth2.clients.auth0.scopes[1]=profile
micronaut.security.oauth2.clients.auth0.scopes[2]=email
micronaut.security.oauth2.clients.auth0.grant-type=authorization_code
micronaut.security.endpoints.logout.get-allowed=true
micronaut.security.redirect.unauthorized.url=/oauth/login/auth0
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allow-credentials=true
micronaut.test.resources.enabled=false