spring.application.name=server
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
okta.oauth2.issuer="https://127.0.0.1:8080/"
okta.oauth2.client-id="4RReX2otLdCWHpNMl1Z39Xn5mPTdMJL5"
okta.oauth2.client-secret="onhrfVWSLZlUV2a2SRn4STGSmeiLZ7EQfLP2Yw5JOzdl2tbHZETUIVXmlIzJN7_9"