micronaut.security.redirect.login-success=https://www.interviewdocs.net/home
micronaut.server.cors.configurations.web.allowed-origins[0]=https://www.interviewdocs.net
micronaut.security.token.cookie.cookie-secure=true
micronaut.security.token.cookie.cookie-same-site=None