micronaut.application.name=server
micronaut.security.enabled=true
micronaut.security.token.cookie.enabled=true
micronaut.security.token.cookie.cookie-http-only=true
micronaut.security.authentication=idtoken
micronaut.security.oauth2.clients.auth0.client-id=J49enmYEIqkzDdzS7gFPXIn4CbPpdKKy
micronaut.security.oauth2.clients.auth0.client-secret=${AUTH0_CLIENT_SECRET}
micronaut.security.oauth2.clients.auth0.scopes[0]=openid
micronaut.security.oauth2.clients.auth0.scopes[1]=profile
micronaut.security.oauth2.clients.auth0.scopes[2]=email
micronaut.security.oauth2.clients.auth0.grant-type=authorization_code
micronaut.security.endpoints.logout.get-allowed=true
micronaut.security.redirect.unauthorized.url=/oauth/login/auth0
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allow-credentials=true
micronaut.test.resources.enabled=false
datasources.default.maximum-pool-size=1
datasources.default.minimum-idle=0
datasources.default.idle-timeout=10000
datasources.default.max-lifetime=300000