datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.password=${DB_PASSWORD}
datasources.default.url=jdbc:postgresql://${DB_HOST}:5432/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}
datasources.default.username=${DB_USERNAME}
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
jpa.default.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
jpa.default.properties.hibernate.jdbc.time_zone=UTC
micronaut.application.name=server
micronaut.security.enabled=true
micronaut.security.token.cookie.enabled=true
micronaut.security.token.cookie.cookie-http-only=true
micronaut.security.token.cookie.cookie-secure=false
micronaut.security.token.cookie.cookie-same-site=Lax
