name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy_client:
    name: Deploy client to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::529710251809:role/InterviewDocsGithubOIDC
        role-session-name: GitHub_to_AWS_via_OIDC
        aws-region: us-east-1
    
    - name: Node.js Setup
      uses: actions/setup-node@v4
      with:
        node-version: 24.11.0

    - name: Dependency Installation
      run: cd ./client && npm install && npm install -g @angular/cli
  
    - name: Client Build
      run: cd ./client && ng build --configuration production
      env:
        NG_APP_VIDEO_S3_BUCKET: ${{ secrets.NG_APP_VIDEO_S3_BUCKET }}
        NG_APP_AUTH0_ISSUER: ${{ secrets.NG_APP_AUTH0_ISSUER }}
        NG_APP_AUTH0_CLIENT_ID: ${{ secrets.NG_APP_AUTH0_CLIENT_ID }}

    - name: Deploy build to AWS S3
      run: |
        aws s3 sync ./client/dist/client/browser/ ${{ secrets.S3_CLIENT_BUCKET }} --delete 
        aws s3 sync ./client/dist/client/ ${{ secrets.S3_CLIENT_BUCKET}} --exclude "browser/*"
    
    - name: Create CloudFront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.STATIC_DISTRIBUTION_ID }} --paths "/*"

    - name: Cancel workflow on failure
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.5
      
  deploy_server:
    name: Deploy server jar to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::529710251809:role/InterviewDocsGithubOIDC
        role-session-name: GitHub_to_AWS_via_OIDC
        aws-region: us-east-1
    
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Server Build with Gradle Wrapper
      run: cd ./server && gradle shadowJar
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

    - name: Deploy build to S3
      run:  aws s3 cp ./server/build/libs/server-0.1-all.jar ${{ secrets.S3_SERVER_BUCKET }}/server-0.1-all.jar
    
    - name: Update function code in Lambda
      run: aws lambda update-function-code --function-name interviewdocs-micronaut --s3-bucket interviewdocs-jar --s3-key server-0.1-all.jar --s3-object-storage-mode COPY
    
    - name: Cancel workflow on failure
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.5
    